Repository openshift/aws-ebs-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#171 Bug 1879192: Make EBS volume expansion idempotent
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#173 Updating ose-aws-ebs-csi-driver builder & base images to be consistent with ART
  Dockerfile.openshift.rhel7
Labels: approved, lgtm

#174 Bug 1876935: UPSTREAM: 568: Apply extra volume tags to EBS snapshots
  cmd/main.go
  cmd/options/controller_options.go
  cmd/options_test.go
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/driver_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
